### ISSUE TITLE
Standardise our nomenclature: 'ratings' rater than 'annotation'

### ISSUE THREAD

**Issue by dvukcevic** [jeffreypullin/rater#10]
I'd like to see greater consistency with the terms we use and how we describe the package.

In particular, often we talk about **ratings** but sometimes we instead talk about **annotation**.  How about we standardise on using 'ratings' throughout, but in the high-level documentation (e.g. README, DESCRIPTION) we can mention alternative nomenclature, such as 'annotation', 'gradings', etc.

**Comment by Voltemand** [comment]
I completely agree I've been very conscious of this imprecision - I'll make it a priority as I write/rewrite the vignettes and other materials.

**Comment by jeffreypullin** [comment]
Fixed (mostly) in 89c7a98
