### ISSUE TITLE
Better documentation and formatting of included data

### ISSUE THREAD

**Issue by dvukcevic** [jeffreypullin/rater#12]
For any dataset we include (currently only `anesthesia`), we should:

- Provide full references/citations to the source
- Use more meaningful column labels

Basically, the dataset and its documentation should be able to stand alone from the package, so they are usable and understandable even for someone not using any of the functionality of the rest of the package.

**Comment by jeffreypullin** [comment]
We can include some of the text + citations from the paper when it is completed
