### ISSUE TITLE
Changes to theta plot

### ISSUE THREAD

**Issue by jeffreypullin** [jeffreypullin/rater#120]
cc @dvukcevic 

The theta plot is a foundational part of `rater` but I think we can improve it.

1. I would like to include Rater 1, ..., Rater K in the top facet labels, rather than the 1..K we have now.

2. Currently we include numbers on the plot. This makes the actual values of the plot easier to see but means the plot looks really bad when 'shrunk'. This is a particular problem when we try to put i.e. the pi and theta plots together (see below). We could remove the numbers in this situation and instead have a legend for the colour, what do you think?

(I am thinking about putting multiple plots on one page because I am not happy with the way we present the three plots currently as separate plots) 

The current theta plot (normal size):

![image](https://user-images.githubusercontent.com/34267114/97257389-e0f94f80-1869-11eb-9912-dd78b9b9aec5.png)

when shrunk:

![image](https://user-images.githubusercontent.com/34267114/97257540-5bc26a80-186a-11eb-95ed-e63c9b69f9fd.png)

Multiple plots (with the new pi plot because I'm still on that branch)

![image](https://user-images.githubusercontent.com/34267114/97257678-b78cf380-186a-11eb-8a07-60e023b5dd95.png)

**Comment by dvukcevic** [comment]
@jeffreypullin Both of these ideas sound good to me.  As long as we retain the ability to put numbers in (handy to have when the numbers are legible) and to easily create any plot any separately (rather than together), then I think these new ideas would be great features to have.
