### ISSUE TITLE
Allow wide data as input

### ISSUE THREAD

**Issue by jeffreypullin** [jeffreypullin/rater#144]
Currently we only allow two types of data as input to rater: `long` and `grouped`.

`long` is the default and is intended as the standard format while `grouped` is implemented so that the more efficient version of the likelihood can be used. In `rater()` the user can specify the data format they are passing or by default the function will assume the user is passing `long` data. The passed data format is used to know how to validate and ultimate parse the data into the format the stan models want.

The big downside of this approach is that if the user has `wide` data which is probably the most common format the data we are interested in exists 'in the wild' it is difficult for them to use {rater}. We don't allow them to pass their wide data to `rater()` and we don't even give them any utility functions to convert their data to long format. 

On reflection I think this is probably a major usability issue for {rater} and one we should address. Here are some options for how we could:

1. Provide a utility function `wide_to_long()` to convert wide data to the long format. 
  Pros: 
    * No changes to current interface required
   Cons:
    * Probably hard to discover - though #23 would help
 
2. Add a new `data_format` option to `rater()`: `wide`, possibly as the default
  Pros:
    * Very easy for users who have wide data
  Cons: 
    * Slightly more implementation work but shouldn't be to bad
    * Would be breaking change for users (though we don't have too many atm) 
    * Harder for users with long data

Ultimately I think the decision depends on which format of data we believe is more common in the wild. My suspicion is that wide data is the default and I therefore am in favor of 2. even if we have to make a breaking change.

Thoughts @dvukcevic?

**Comment by jeffreypullin** [comment]
Also curious if this was a problem for you/ what format your data was in @Agasax

**Comment by jeffreypullin** [comment]
One (important!) thing I had forgotten yesterday: the reason we prefer long data is that it can represent situations where one rater rates an item more than once. (i.e. in the `anesthesia` data). Given this I don't think it makes sense to make `wide` data the default, but I do think that it would be good to implement `data_format = "wide"` in `rater()`.

**Comment by dvukcevic** [comment]
Very perceptive, @jeffreypullin.  I agree we should provide some means to use wide data.

I was going to suggest that you start by implementing your first suggestion initially, but I see you have already implemented both (in #145).  I agree with keeping the long format as the default.

**Comment by Agasax** [comment]
> Also curious if this was a problem for you/ what format your data was in @Agasax

My raw data is wide, but I don't have a problem wrangling it to long format (as I do for other purposes as well).
