### ISSUE TITLE
Change (swap?) summary/print methods

### ISSUE THREAD

**Issue by jeffreypullin** [jeffreypullin/rater#45]
Right now, the print method for a `rater_fit` object is very verbose, including information about the prior and the output of `print` on the underlying Stan model. In contrast the `summary` method is short, only providing the name of the rater model. This was basically done to align with the behavior of `print`/`summary` on the underlying stan model. 

However, this behavior is different to the canonical statistical model in R: `lm()` which has a more verbose summary method. 

``` r
test <- lm(1 ~ 1)
# Call the print method.
test
#> 
#> Call:
#> lm(formula = 1 ~ 1)
#> 
#> Coefficients:
#> (Intercept)  
#>           1
# Call the summary method.
summary(test)
#> 
#> Call:
#> lm(formula = 1 ~ 1)
#> 
#> Residuals:
#> ALL 1 residuals are 0: no residual degrees of freedom!
#> 
#> Coefficients:
#>             Estimate Std. Error t value Pr(>|t|)
#> (Intercept)        1         NA      NA       NA
#> 
#> Residual standard error: NaN on 0 degrees of freedom
```

<sup>Created on 2020-05-14 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I became concerned about this because as the output from the current `print` function is verbose I wanted a way to limit it for the paper output. I think an interface through summary would be more intuitive for limiting output. 

@dvukcevic

**Comment by dvukcevic** [comment]
I agree that making the `print()` output briefer than `summary()` would be preferable.

**Comment by jeffreypullin** [comment]
I should also remove the dependency on {rstan}'s print method.

**Comment by dvukcevic** [comment]
Nice work, @jeffreypullin!

I like how the new `summary()` method displays both the MAP for z and the class probabilities.
