### ISSUE TITLE
Implement posterior draws extraction

### ISSUE THREAD

**Issue by jeffreypullin** [jeffreypullin/rater#56]
We need an interface to extract the posterior draws.

{rstanarm} uses `as.matrix`, `as.dataframe` etc, to 'coerce' the fit object to draws. I'm *not* a fan of this interface. Instead I plan to implement `posterior_draws()` for consistency with `posterior_interval` etc.

**Comment by jeffreypullin** [comment]
Fixed by #58

**Comment by dvukcevic** [comment]
I find the word 'draws' to be a bit too colloquial.  Perhaps 'samples' would be more appropriate?  So, would it be better to call this function `posterior_samples()`?

**Comment by dvukcevic** [comment]
From #69, it sounds like you agree. :-)

**Comment by jeffreypullin** [comment]
Yep, forgot to link back to this.
