### ISSUE TITLE
Implement posterior_intervals

### ISSUE THREAD

**Issue by jeffreypullin** [jeffreypullin/rater#59]
How to use a foreign generic?

**Comment by jeffreypullin** [comment]
Another thought: does it make sense to calculate this for the conditional probabilities of z? What would the interpretation of that interval be?

**Comment by jeffreypullin** [comment]
Fixed by #62

**Comment by dvukcevic** [comment]
There are still some issues with this:

- [ ] Use of undefined `fit` local variable
- [ ] Need to define a `posterior_interval()` generic function
