### ISSUE TITLE
Newlines in cat() output

### ISSUE THREAD

**Issue by dvukcevic** [jeffreypullin/rater#68]
When we use `cat()`, usually we need to explicitly include newline characters (`\n`).  This is currently what we do in most cases.

I noticed two things:

* The `summary()` methods currently don't include newlines. This is not noticeable in R Markdown output (I think R Markdown automatically adds missing newlines at the end of any output) but is a problem when using the methods on the command-line.

* `cat()` has an argument called `fill` which when set to `TRUE` will add newlines, and also wrap output to the desired text width.

I'm not sure what is considered best practice.  Using `fill = TRUE` seems desirable to me.  Perhaps we should set it as much as possible when using `cat()`?

Otherwise, at least we need to fix the `summary()` methods to include newlines.

**Comment by jeffreypullin** [comment]
I will keep this in mind when I tackle #45

**Comment by jeffreypullin** [comment]
Has this been fixed by the recent changes to the summary method @dvukcevic? 

If not, can you give me an example of the where there is sub-optimal output.

**Comment by dvukcevic** [comment]
No, the only thing that has happened is that the issue has now moved to the `print()` method rather than the `summary()` method.  Here's an example:

```r
> print(fit)
Bayesian Dawid and Skene Model with MCMC draws.>
```

Note that the command-line prompt occurs to the right of the message, rather than on a new line.

**Comment by jeffreypullin** [comment]
Right, so I couldn't reproduce that in RStudio but I could at a prompt in a terminal. 

I think it's now fixed on master (I just added some newlines)

**Comment by jeffreypullin** [comment]
@dvukcevic when you get a chance could you please check whether this is fixed?

**Comment by dvukcevic** [comment]
Yes, this works fine now.
