### ISSUE TITLE
Extracting output fails for optimisation fits on grouped data

### ISSUE THREAD

**Issue by dvukcevic** [jeffreypullin/rater#79]
When analysing the `caries` data (which is in 'grouped' format), `plot_z()` and `point_estimate()` both fail for MAP model fits, giving the following error message:

```
Error in matrix(log_p_z_values, nrow = stan_data$I, ncol = stan_data$K): non-numeric matrix extent
```

**Comment by jeffreypullin** [comment]
I can't seem to reproduce this on master. The following works for me: 

```r
fit <- rater(caries, "dawid_skene", method = "optim")
point_estimate(fit, pars = "z")
$z
 [1] 1 3 2 2 2 2 1 3 2 2 4 2 1 2 1 1 1 1 2 2 2 2 2 2 1 1 2 1 1 1 1 3 1 2 2 3 2 2 3 1 1 1
[43] 2 1 2
```

**Comment by dvukcevic** [comment]
Hmm...I wonder if we're on the same master or not, but here's what I currently get:

```r
> fit <- rater(caries, "dawid_skene", method = "optim")
Error: `data` must have exactly three columns.
> fit <- rater(caries, "dawid_skene", method = "optim", data_format = "grouped")
Error: Grouped data can only be usesed with the Dawid and Skene model
```

So, there are some more fundamental bugs to fix.  :-)

**Comment by dvukcevic** [comment]
On the other hand, I currently get this:

```r
> fit <- rater(caries, dawid_skene(), method = "optim", data_format = "grouped")
> point_estimate(fit, pars = "z")
Error in matrix(log_p_z_values, nrow = I, ncol = K) : 
  invalid 'nrow' value (too large or NA)
In addition: Warning messages:
1: In max(fit$data$item) : no non-missing arguments to max; returning -Inf
2: In max(fit$data$rating) :
  no non-missing arguments to max; returning -Inf
3: In matrix(log_p_z_values, nrow = I, ncol = K) :
  NAs introduced by coercion to integer range
```

I wonder if it's another R version problem?

**Comment by dvukcevic** [comment]
I think the bug is that `class_probabilities.optim_fit()` assumes long data.  It expects the `data` data frame to have columns called `item` and `rating`.

**Comment by jeffreypullin** [comment]
Oh, yeah right - can reproduce it now. This was introduced by changing how we 'remember' the data dimensions. The fix is simplish but will require some rewiring.
