### ISSUE TITLE
Prevalence typo, plot fails

### ISSUE THREAD

**Issue by dvukcevic** [jeffreypullin/rater#82]
There are some instances of the word 'prevalence' being misspelt, for example as 'prevelance'.

Mostly this is harmless (and should be fixed at some point, but not urgent).  However, one such typo causes a bug: the function `plot.rater_fit()` has a line:

    "prevelance" = plot_pi(x)

This misspelling will cause commands of the form `plot(fit, "prevalence")` to fail.

**Comment by jeffreypullin** [comment]
Fixed by #85

**Comment by jeffreypullin** [comment]
Fixed by #85
