### ISSUE TITLE
Specify model using a string

### ISSUE THREAD

**Issue by dvukcevic** [jeffreypullin/rater#83]
Current we specify the model we want by passing a function, for example `dawid_skene()` in:

```R
rater(anesthesia, dawid_skene())
```

This might feel a bit intimidating for non-experts. How about we change to specifying the model as a character vector?  For example:

```R
rater(anesthesia, "dawid-skene")
```

**Comment by jeffreypullin** [comment]
Your point about intimidating non-experts in a good one, but there are some reasons for sticking with the current interface. 

1. The point of the current interface is to allow the user to pass values of the prior parameters without cluttering the signature of `rater()`. Example usage:

```r
fit <- rater(my_data, dawid_skene(alpha = my_alpha, beta = my_beta)
```

If we didn't use the function approach the prior parameters would 'float free' and the signature of rater would have to include all the prior parameters. The current approach also makes it easier to programmatically try different prior combinations though I guess this is of limited value. 

2. There is some precedent for this sort of interface in base R. Consider the following:

```r
fit <- glm(y ~ x, data = data, family = binomial(link = "identity")
```
statistically not very sensible, but valid. `family` can be a function with arguments. 

I think however there is a middle ground: we can support string arguments for which we assume default priors, yet still allow the creation and passing of model objects (i.e. the functions) This is actually also what `glm` does (I discovered this when reading the glm help page while writing the last example - though they also allow bare calls which I **don't** think we should do.) 

So under this proposal:

```r
rater(anesthesia, "dawid-skene")
```

would be valid and the same as the following, which would also be accepted:

```r
rater(anesthesia, dawid_skene())
```
In addition invocations like the following would also be valid:

```r
rater(anesthesia, dawid_skene(alpha = my_alpha, beta = my_beta))
```
How does that sound?

**Comment by dvukcevic** [comment]
Sounds perfect!

Your first point about not cluttering up the signature of `rater()` is a good one.  That's a very nifty feature.

I am aware of the dual nature of `glm()` and indeed had it in mind.  In my scripts I typically use the 'simpler' interface to it, for example:

```r
fit <- glm(y ~ x, data = data, family = "binomial")
```

Having the option of something simpler for newbies and a more powerful option for experts sounds like the way to go.

**Comment by jeffreypullin** [comment]
Yes, sorry I am sure you were aware! I wasn't until recently - I stole the trick from greta.
